
theme = "autumn_night"


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-1 = ":bn"
A-2 = ":bp"
A-q = ":q!"
A-w = ":w!"
A-b = ":run-shell-command ./build.sh build"
A-d = ":run-shell-command ./build.sh debug"
A-r = ":run-shell-command ./build.sh run"
A-k = ":run-shell-command pkill main"
"A-," = "page_cursor_half_up"
"A-." = "page_cursor_half_down"



[keys.normal.space]
"1" = ":buffer-close-others!"
"2" = ":quit"
"3" = ":hsplit"
"4" = ":vsplit"



[editor]
line-number = "relative"
mouse = true
gutters = []
#idle-timeout = 10
completion-timeout = 10
lsp.display-inlay-hints = true

[editor.file-picker]
hidden = false
