
theme = "modus_vivendi_tritanopia"


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-1 = ":bn"
A-2 = ":bp"
A-q = ":q!"
A-w = ":w!"
A-b = ":run-shell-command make"
A-n = ":run-shell-command zellij run -- make debug"
A-s = ":run-shell-command g++ -g sol sol.cpp && ./sol"



[keys.normal.space]
"1" = ":buffer-close-others!"
"2" = ":quit"
"3" = ":hsplit"
"4" = ":vsplit"



[editor]
line-number = "relative"
mouse = true
gutters = []
#idle-timeout = 10
completion-timeout = 10

[editor.file-picker]
hidden = false
