
[[language]]
name = "cpp"
scope = "source.cpp"
file-types = ["cpp", "cxx", "cc", "h", "hpp"]
roots = ["compile_commands.json", ".git", ".hg"]
auto-format = true
language-servers = [ "clangd" ]
injection-regex = "cpp"
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "python"
scope = "source.py"
file-types = ["py"]
roots = [".git"]
auto-format = true
language-servers = ["pyright"]
injection-regex = "py"
indent = { tab-width = 4, unit = "  " }
[language-server.pyright.config.pyright]
plugins.black.enabled = true


[[language]]
name = "odin"
#auto-format = false
scope = "scope.odin" # "source.odin"
file-types = ["odin"]
roots = ["ols.json"]
language-servers = [ "ols" ]
comment-token = "//"
indent = { tab-width = 2, unit = " " }
injection-regex = "odin"
formatter = { command = "odinfmt", args = [ "-stdin", "true" ] }



