
[[language]]
name = "cpp"
scope = "source.cpp"
file-types = ["cpp", "cxx", "cc", "h", "hpp"]
roots = ["compile_commands.json", ".git", ".hg"]
auto-format = true
language-servers = [ "clangd" ]
injection-regex = "cpp"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "python"
scope = "source.py"
file-types = ["py"]
roots = [".git"]
auto-format = true
language-servers = ["pyright"]
injection-regex = "py"
indent = { tab-width = 2, unit = "  " }
[language-server.pyright.config.pyright]
plugins.black.enabled = true


